apiVersion: v2
name: workastra
description: A unified Helm chart for Workastra services (desk, iam, migration).
type: application
version: 0.1.0
appVersion: "0.1.0"
icon: https://github.com/workastra
