global:
  tenant:
    scheme: http
    domain: workastra.com

desk:
  install: true
  
  httpRoute:
    enabled: true
    annotations: {}
    hostnames:
      - workastra.com
    parentRefs:
      - name: eg
        namespace: default
        sectionName: http
    rules:
      - matches:
        - path:
            type: PathPrefix
            value: /

  secrets:
    # The first value in the keys array will be used as the current app key, while the rest will be treated as previous keys for rotation purposes.
    keys: []
    oauth2:
      # This secret is used for the OAuth2 client secret in the desk application.
      clientSecret: ""
