# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

includes:
  prepare:
    taskfile: ./roles/prepare.Taskfile.yml
  gateway:
    taskfile: ./roles/gateway.Taskfile.yml
  postgres:
    taskfile: ./roles/postgres.Taskfile.yml
  workastra:
    taskfile: ./roles/workastra.Taskfile.yml

vars:
  TENANT_NAME: '{{ .TENANT_NAME | default "workastra" }}'
  DOMAIN: '{{ .DOMAIN | default "workastra.com" }}'
  MIGRATION_IMAGE_REPOSITORY: '{{ .MIGRATION_IMAGE_REPOSITORY | default "docker.io/workastra/platform/migration" }}'
  MIGRATION_IMAGE_TAG: '{{ .MIGRATION_IMAGE_TAG | default "latest" }}'
  DESK_IMAGE_REPOSITORY: '{{ .DESK_IMAGE_REPOSITORY | default "docker.io/workastra/desk" }}'
  DESK_IMAGE_TAG: '{{ .DESK_IMAGE_TAG | default "latest" }}'
  IAM_IMAGE_REPOSITORY: '{{ .IAM_IMAGE_REPOSITORY | default "docker.io/workastra/platform/iam" }}'
  IAM_IMAGE_TAG: '{{ .IAM_IMAGE_TAG | default "latest" }}'

tasks:
  deploy:
    cmds:
      - task: prepare:ns
      - task: gateway:deploy
      - task: postgres:deploy
      - task: workastra:deploy
