apiVersion: v1
kind: Secret
metadata:
  name: {{ include "desk.fullname" . }}
  labels:
    {{- include "desk.labels" . | nindent 4 }}
type: Opaque
stringData:
  app_key: {{ first .Values.secrets.keys | default "" | quote }}
  {{- if rest .Values.secrets.keys }}
  previous_keys: |
    {{- rest .Values.secrets.keys | join "\n" | nindent 2 }}
  {{- else }}
  previous_keys: ""
  {{- end }}
  oauth2_client_secret: {{ .Values.secrets.oauth2.clientSecret }}
