apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "workastra.desk.fullname" . }}
  labels:
    {{- include "workastra.desk.labels" . | nindent 4 }}
data:
  .env.production: |
    APP_URL={{ .Values.global.tenant.scheme }}://{{ .Values.global.tenant.domain }}
    IAM_EXTERNAL_ISSUER_URL={{ .Values.global.tenant.scheme }}://{{ .Values.global.tenant.domain }}/iam
    IAM_INTERNAL_ISSUER_URL=http://workastra-iam.workastra.svc.cluster.local:9000
    IAM_TLS_SKIP_VERIFY=true
    IAM_OAUTH_CLIENT_ID=workastra-desk
    LOCK_MODE=in-memory
