{{- if and .Values.desk.enabled .Values.desk.httpRoute.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "workastra.desk.fullname" . }}
  labels:
    {{- include "workastra.desk.labels" . | nindent 4 }}
spec:
  parentRefs:
    {{- .Values.desk.httpRoute.parentRefs | toYaml | nindent 4 }}
  hostnames:
    {{- .Values.desk.httpRoute.hostnames | toYaml | nindent 4 }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /iam
      backendRefs:
        - name: {{ include "workastra.iam.fullname" . }}
          port: {{ .Values.iam.service.port }}
          weight: 1
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ include "workastra.desk.fullname" . }}
          port: {{ .Values.desk.service.port }}
          weight: 1
{{- end }}
