{{- if .Values.desk.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "workastra.desk.fullname" . }}
  labels:
    {{- include "workastra.desk.labels" . | nindent 4 }}
type: Opaque
stringData:
  app_key: {{ first .Values.desk.secrets.keys | default "" | quote }}
  {{- if rest .Values.desk.secrets.keys }}
  previous_keys: |
{{ rest .Values.desk.secrets.keys | join "\n" | indent 4 }}
  {{- else }}
  previous_keys: ""
  {{- end }}
  oauth2_client_secret: {{ .Values.desk.secrets.oauth2.clientSecret }}
{{- end }}
