apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "workastra.iam.fullname" . }}
  labels:
    {{- include "workastra.iam.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.iam.replicaCount }}
  selector:
    matchLabels:
      {{- include "workastra.iam.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "workastra.iam.labels" . | nindent 8 }}
    spec:
      containers:
        - name: iam
          image: "{{ .Values.iam.image.repository }}:{{ .Values.iam.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: {{ .Values.iam.service.port }}
              protocol: TCP
          {{- with .Values.iam.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.iam.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.iam.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.iam.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgresql-rw.workastra.svc.cluster.local:5432/workastra?currentSchema=workastra"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgresql-credentials
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-credentials
                  key: password
      {{- with .Values.iam.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.iam.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.iam.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.iam.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
