apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "workastra.migration.fullname" . }}
  labels:
    {{- include "workastra.migration.labels" . | nindent 4 }}
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migration
          image: "{{ .Values.migration.image.repository }}:{{ .Values.migration.image.tag }}"
          imagePullPolicy: IfNotPresent
          {{- with .Values.migration.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
