apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "migration.fullname" . }}
  labels:
    {{- include "migration.labels" . | nindent 4 }}
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migration
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
